[build]
  publish = "."
  command = "echo 'Build completed - static site'"

# Désactiver le scan de secrets pour ce projet
[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_PATHS = "*.md,netlify/functions/*"

# Redirection ads.txt vers Ezoic
[[redirects]]
  from = "/ads.txt"
  to = "https://srv.adstxtmanager.com/19390/kironpass.com"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
