[build]
  publish = "."
  command = "echo 'Build completed - static site'"

# Désactiver le scan de secrets pour ce projet
[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_PATHS = "*.md,netlify/functions/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
