[build]
  publish = "."
  command = "echo 'Build completed - static site'"

# Désactiver le scan de secrets pour ce projet
[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_PATHS = "*.md,netlify/functions/*"

# Headers pour sitemap et robots
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    X-Robots-Tag = "noindex"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"

# Redirection ads.txt vers Ezoic
[[redirects]]
  from = "/ads.txt"
  to = "https://srv.adstxtmanager.com/19390/kironpass.com"
  status = 301
  force = true

# Redirection par défaut (sauf pour les fichiers existants)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
