// ===================== LISTES DE MOTS POUR PASSPHRASE =====================
// Liste complète de mots français et anglais (A-Z)

const wordListsFR = [
    // A
    'abandon', 'abeille', 'abri', 'absence', 'absolument', 'accent', 'accepter', 'accident',
    'accord', 'accuser', 'acheter', 'acide', 'acier', 'action', 'acteur', 'actrice',
    'adapter', 'addition', 'adieu', 'admirer', 'adopter', 'adorer', 'adresse', 'adulte',
    'aer', 'affaire', 'affiche', 'agence', 'agenda', 'agent', 'agir', 'agiter',
    'agneau', 'agricole', 'aide', 'aider', 'aigle', 'aiguille', 'ail', 'aile',
    'ailleurs', 'aimer', 'ainsi', 'aise', 'ajouter', 'alarme', 'album', 'alcool',
    'alerte', 'algue', 'aliment', 'aller', 'alliance', 'allonger', 'allumer', 'alors',
    'alphabet', 'altitude', 'aluminium', 'amande', 'amateur', 'ambassade', 'ambiance', 'ambre',
    'ambulance', 'amer', 'ami', 'amitie', 'amour', 'ampoule', 'amuser', 'ancien',
    'ancre', 'ange', 'anglais', 'angle', 'animal', 'anneau', 'annonce', 'annuel',
    'anorak', 'antenne', 'antique', 'anxieux', 'apercevoir', 'aplatir', 'apologie', 'appareil',
    // B
    'bagage', 'bague', 'baignade', 'baigner', 'baiser', 'baisser', 'balai', 'balance',
    'balcon', 'baleine', 'balle', 'ballon', 'bambou', 'banane', 'banc', 'bande',
    'bandit', 'banlieue', 'banque', 'banquet', 'barbe', 'baril', 'baron', 'barque',
    'barre', 'barreau', 'barriere', 'bas', 'base', 'bassin', 'bataille', 'bateau',
    'batiment', 'baton', 'battre', 'bavard', 'bazar', 'beau', 'beaucoup', 'beaute',
    'bebe', 'bec', 'beige', 'beignet', 'belier', 'belle', 'benefice', 'benir',
    'berceau', 'berger', 'besoin', 'betail', 'bete', 'beton', 'beurre', 'biberon',
    'bible', 'bicyclette', 'bidon', 'bien', 'bientot', 'biere', 'bijou', 'bilan',
    'bille', 'billet', 'biologie', 'biscuit', 'bison', 'bissextile', 'bizarre', 'blague',
    'blanc', 'blanchir', 'blason', 'blesse', 'blesser', 'bleu', 'bloc', 'blond',
    'bloquer', 'blouse', 'blouson', 'bobine', 'bocal', 'boeuf', 'boire', 'bois',
    // C
    'cabane', 'cabine', 'cable', 'cacao', 'cacahouete', 'cacher', 'cachet', 'cachette',
    'cactus', 'cadavre', 'cadeau', 'cadenas', 'cadence', 'cadet', 'cadran', 'cadre',
    'cafard', 'cafe', 'cafeteria', 'cage', 'cagou', 'cahier', 'caillou', 'caisse',
    'calcul', 'calendrier', 'calme', 'calmer', 'calorie', 'camarade', 'camion', 'camp',
    'campagne', 'camper', 'camping', 'canal', 'canape', 'canard', 'candidat', 'canne',
    'cannelle', 'canon', 'canot', 'cantine', 'canton', 'caoutchouc', 'capable', 'cape',
    'capital', 'capitaine', 'caprice', 'capsule', 'capter', 'captif', 'capturer', 'capuche',
    'carabine', 'caractere', 'caramel', 'caravane', 'carbone', 'carcasse', 'cardinal', 'caresse',
    'cargaison', 'cargo', 'carnaval', 'carnet', 'carotte', 'carre', 'carreau', 'carrefour',
    'carriere', 'carriole', 'carte', 'carton', 'cas', 'cascade', 'caserne', 'casier',
    'casque', 'cassette', 'casser', 'casserole', 'castor', 'catalogue', 'catastrophe', 'categorie',
    // D
    'dague', 'daigner', 'daim', 'dalle', 'dame', 'damier', 'danger', 'dangereux',
    'dans', 'danse', 'danser', 'danseur', 'date', 'dater', 'datte', 'dauphin',
    'davantage', 'debacle', 'deballer', 'debat', 'debattre', 'debarrasser', 'debile', 'debit',
    'debiter', 'deblayer', 'deboire', 'deborder', 'deboucher', 'debout', 'debrouiller', 'debut',
    'debuter', 'decembre', 'decennie', 'decent', 'deception', 'decevoir', 'dechainer', 'decharge',
    'dechausser', 'dechets', 'dechiffrer', 'dechirer', 'decidement', 'decider', 'decimale', 'decision',
    'declamer', 'declarer', 'declasser', 'declencher', 'declic', 'decoller', 'decolorer', 'decombres',
    'decor', 'decorer', 'decoudre', 'decouper', 'decourager', 'decouvrir', 'decreter', 'decrire',
    'decrocher', 'decroitre', 'decu', 'dedaigner', 'dedans', 'dedicace', 'dedier', 'dedommager',
    'dedoubler', 'deduire', 'deesse', 'defaire', 'defaite', 'default', 'defavorable', 'defaut',
    // E
    'eau', 'ebahi', 'ebauche', 'ebene', 'eblouir', 'eboueur', 'ebranler', 'ebrecher',
    'ebullition', 'ecaille', 'ecaler', 'ecarlate', 'ecarquiller', 'ecart', 'ecarter', 'ecchymose',
    'echange', 'echanger', 'echantillon', 'echapper', 'echarde', 'echarpe', 'echasse', 'echauder',
    'echauffer', 'echec', 'echelle', 'echelon', 'echeveau', 'echine', 'echiquier', 'echo',
    'echouer', 'eclabousser', 'eclair', 'eclairage', 'eclaircir', 'eclairer', 'eclat', 'eclater',
    'eclipse', 'eclore', 'ecluse', 'ecoeurer', 'ecole', 'ecolier', 'economie', 'economiser',
    'ecorce', 'ecorcher', 'ecossais', 'ecouter', 'ecran', 'ecraser', 'ecremé', 'ecrevisse',
    'ecrire', 'ecriteau', 'ecriture', 'ecrivain', 'ecrou', 'ecrouler', 'ecueil', 'ecuelle',
    'ecurie', 'ecusson', 'ecureuil', 'edenter', 'edifier', 'edit', 'editeur', 'edition',
    'edredon', 'education', 'eduquer', 'effacer', 'effectif', 'effectuer', 'effet', 'efficace',
    // F
    'fable', 'fabrication', 'fabriquer', 'fabuleux', 'facade', 'face', 'facette', 'facile',
    'faciliter', 'facilite', 'facture', 'facteur', 'faible', 'faiblir', 'faience', 'faillir',
    'faim', 'faire', 'faisan', 'fait', 'falaise', 'falloir', 'falot', 'falsifier',
    'fameux', 'familial', 'familier', 'famille', 'famine', 'fanfare', 'faner', 'fantaisie',
    'fantastique', 'fantome', 'faon', 'farceur', 'farce', 'farcir', 'fardeau', 'farfelu',
    'farine', 'farouche', 'fasciner', 'fatal', 'fatigant', 'fatigue', 'fatiguer', 'faubourg',
    'faucher', 'faucille', 'faucon', 'faufiler', 'faune', 'faussaire', 'fausser', 'fausset',
    'faute', 'fauteuil', 'fautif', 'fauve', 'faux', 'faveur', 'favorable', 'favori',
    'favoriser', 'fecond', 'feconder', 'federatif', 'federation', 'feerique', 'feindre', 'feinte',
    'feler', 'feliciter', 'felin', 'femelle', 'feminin', 'femme', 'fenaison', 'fendre',
    // G
    'gabarit', 'gacher', 'gachette', 'gadget', 'gaffe', 'gaffeur', 'gage', 'gager',
    'gagnant', 'gagner', 'gai', 'gaieté', 'gaillard', 'gain', 'gaine', 'gala',
    'galant', 'galaxie', 'galere', 'galerie', 'galet', 'galette', 'galoper', 'galop',
    'gambader', 'gamelle', 'gamin', 'gamme', 'gant', 'garage', 'garant', 'garantir',
    'garcon', 'garde', 'garder', 'gardien', 'gare', 'garer', 'garnir', 'garniture',
    'gasoline', 'gaspiller', 'gastronomie', 'gateau', 'gater', 'gaterie', 'gauche', 'gaufre',
    'gaulois', 'gave', 'gaz', 'gazelle', 'gazon', 'geant', 'geindre', 'gelatin',
    'gelée', 'geler', 'gemeau', 'gemir', 'gemme', 'genant', 'gencive', 'gendarme',
    'gendre', 'gene', 'gener', 'general', 'generateur', 'generation', 'generosite', 'genereux',
    'genet', 'genial', 'genie', 'genou', 'genre', 'gens', 'gentil', 'gentilhomme',
    // H
    'habile', 'habiller', 'habit', 'habitant', 'habiter', 'habitude', 'habituel', 'habituer',
    'hache', 'hacher', 'hachette', 'hachis', 'hagard', 'haie', 'haillon', 'haine',
    'hair', 'halage', 'hale', 'haleine', 'haler', 'hall', 'halle', 'halte',
    'hamac', 'hameau', 'hameçon', 'hamster', 'hanche', 'handicap', 'hangar', 'hanneton',
    'hanter', 'happer', 'harangue', 'harasser', 'harceler', 'hardi', 'hardiesse', 'haricot',
    'harmonica', 'harmonie', 'harmoniser', 'harnacher', 'harnais', 'harpe', 'harpon', 'hasard',
    'hate', 'hater', 'hatif', 'hausse', 'hausser', 'haut', 'hautain', 'hautbois',
    'hauteur', 'havre', 'hebdomadaire', 'heberger', 'hebeter', 'hectare', 'helas', 'heler',
    'helicopter', 'heliport', 'helium', 'hemisphere', 'hemorragie', 'hennir', 'heraut', 'herbe',
    'herbivore', 'heritage', 'heriter', 'heritier', 'hermine', 'heron', 'heros', 'hesiter',
    // I-J
    'iceberg', 'ideal', 'identique', 'identite', 'idiot', 'idole', 'igloo', 'ignare',
    'ignorer', 'iguane', 'illégal', 'illimité', 'illusion', 'illustrer', 'image', 'imaginer',
    'imbattable', 'imbecile', 'imbiber', 'imiter', 'immédiat', 'immense', 'immeuble', 'immobile',
    'immortel', 'impact', 'impair', 'impatient', 'impeccable', 'imperméable', 'implanter', 'impliquer',
    'implorer', 'impoli', 'important', 'importer', 'imposer', 'impossible', 'impot', 'imprécis',
    'imprimer', 'imprudent', 'impulsion', 'inactif', 'inattendu', 'incapable', 'incendie', 'incident',
    'inciter', 'incliner', 'inclure', 'incolore', 'incommode', 'incomplet', 'inconnu', 'incorrect',
    'incroyable', 'inculper', 'indécis', 'indemnite', 'index', 'indicateur', 'indice', 'indien',
    'jaguar', 'jaillir', 'jalousie', 'jaloux', 'jamais', 'jambe', 'jambon', 'jante',
    'janvier', 'japon', 'japper', 'jardin', 'jardinier', 'jargon', 'jarre', 'jarret',
    // K-L
    'kayak', 'kermesse', 'kerosene', 'kidnapper', 'kilo', 'kilometre', 'kimono', 'kiosque',
    'klaxon', 'koala',
    'label', 'labeur', 'labourer', 'labyrinthe', 'lacet', 'lacher', 'laconique', 'lacune',
    'lagune', 'laicité', 'laid', 'laideur', 'lainage', 'laine', 'laineux', 'laique',
    'laisse', 'laisser', 'lait', 'laitier', 'laitue', 'lambda', 'lambeau', 'lambin',
    'lame', 'lamentable', 'lamenter', 'lampadaire', 'lampe', 'lance', 'lancer', 'lanceur',
    'lancinant', 'landau', 'lande', 'langage', 'lange', 'langouste', 'langue', 'languette',
    'languir', 'laniere', 'lanterne', 'lapin', 'laps', 'laque', 'laquelle', 'larbin',
    'larcin', 'lard', 'lardon', 'large', 'largement', 'largeur', 'larguer', 'larme',
    'larve', 'las', 'lasser', 'lasso', 'latent', 'lateral', 'latin', 'latitude',
    // M
    'machine', 'machoire', 'maçon', 'madame', 'mademoiselle', 'magasin', 'magazine', 'magicien',
    'magie', 'magique', 'magistrat', 'magnétique', 'magnifique', 'magot', 'maigre', 'maigrir',
    'maille', 'maillet', 'maillot', 'main', 'maintenant', 'maintenir', 'maire', 'mairie',
    'mais', 'maison', 'maitre', 'maitrise', 'majeste', 'majeur', 'majorer', 'majorite',
    'majuscule', 'malade', 'maladie', 'maladresse', 'maladroit', 'malaise', 'mâle', 'malediction',
    'malentendu', 'malfaiteur', 'malgre', 'malheur', 'malheureux', 'malhonnete', 'malice', 'malicieux',
    'malin', 'malle', 'mallette', 'malmener', 'malodorant', 'malpropre', 'malsain', 'maltraiter',
    'maman', 'mamelle', 'mammifere', 'mammouth', 'manche', 'manchette', 'manchot', 'mandat',
    'mandarine', 'mandat', 'mandibule', 'mandoline', 'manege', 'manette', 'mangeable', 'mangeoire',
    'manger', 'mangue', 'maniable', 'maniaque', 'manier', 'maniere', 'manifeste', 'manifester',
    // N
    'nage', 'nageoire', 'nager', 'nageur', 'naif', 'nain', 'naissance', 'naitre',
    'naivete', 'nana', 'nanti', 'nappe', 'napperon', 'narguer', 'narine', 'narquois',
    'narrateur', 'narrer', 'nasal', 'naseau', 'nasiller', 'nation', 'national', 'nativite',
    'natte', 'naturaliser', 'nature', 'naturel', 'naufrage', 'naufrager', 'nausée', 'nautique',
    'naval', 'navet', 'navette', 'navigateur', 'naviguer', 'navire', 'navrant', 'nazi',
    'necessaire', 'necessite', 'nectar', 'néerlandais', 'nefaste', 'negatif', 'negligent', 'negliger',
    'negoce', 'negocier', 'negre', 'neige', 'neiger', 'neigeux', 'nenuphar', 'nerf',
    'nerveux', 'nervosité', 'net', 'nettement', 'nettoyer', 'neuf', 'neutre', 'neuvieme',
    'neveu', 'nez', 'niais', 'niche', 'nicher', 'nickel', 'nicotine', 'nid',
    'niece', 'nier', 'nigaud', 'niveau', 'niveler', 'noble', 'noblesse', 'noce',
    // O
    'oasis', 'obeir', 'obeissance', 'obeissant', 'obese', 'objecter', 'objectif', 'objection',
    'objet', 'obligation', 'obliger', 'oblique', 'obliquer', 'obnubiler', 'obscène', 'obscur',
    'obscurcir', 'obscurite', 'obseder', 'obseques', 'observation', 'observer', 'obstacle', 'obstination',
    'obstiner', 'obstruer', 'obtenir', 'obturer', 'obus', 'occasion', 'occasionner', 'occidental',
    'occident', 'occulte', 'occupant', 'occuper', 'occurrence', 'ocean', 'ocre', 'octobre',
    'octroyer', 'oculaire', 'oculiste', 'odeur', 'odieux', 'odorant', 'odyssee', 'oeil',
    'oeillet', 'oeuf', 'oeuvre', 'offense', 'offenser', 'office', 'officiel', 'officier',
    'officieux', 'offrande', 'offre', 'offrir', 'offusquer', 'ogive', 'ogre', 'oie',
    'oignon', 'oiseau', 'oisif', 'oisillon', 'oison', 'oleoduc', 'olfactif', 'olive',
    'olivier', 'olympique', 'ombrage', 'ombre', 'ombrelle', 'omelette', 'omettre', 'omnibus',
    // P
    'pacifier', 'pacifique', 'pacifiste', 'pacte', 'pagaie', 'pagaille', 'page', 'pagode',
    'paie', 'paiement', 'paien', 'paille', 'paillette', 'pain', 'paire', 'paisible',
    'paitre', 'paix', 'palace', 'palais', 'palan', 'pale', 'palefrenier', 'paleontologie',
    'palette', 'paleur', 'palier', 'palir', 'palissade', 'pallier', 'palmares', 'palme',
    'palmier', 'palombe', 'palpable', 'palper', 'palpiter', 'paludisme', 'palombe', 'pamplemousse',
    'panache', 'panacher', 'panaris', 'pancarte', 'pancreas', 'panda', 'pane', 'panier',
    'panique', 'paniquer', 'panne', 'panneau', 'panorama', 'panser', 'pansement', 'pantalon',
    'panthere', 'pantin', 'pantoufle', 'paon', 'papa', 'papal', 'papaye', 'pape',
    'paperasse', 'papeterie', 'papier', 'papillon', 'papillote', 'papoter', 'papyrus', 'paquebot',
    'paquette', 'paquet', 'parachever', 'parachute', 'parade', 'paradis', 'paradoxe', 'parafe',
    // Q-R
    'quadriller', 'quai', 'qualification', 'qualifier', 'qualite', 'quand', 'quant', 'quantite',
    'quarante', 'quarantaine', 'quart', 'quartier', 'quartz', 'quasi', 'quatorze', 'quatre',
    'quatrieme', 'quatuor', 'que', 'quel', 'quelconque', 'quelque', 'quelquefois', 'quelquun',
    'quenouille', 'querelle', 'quereller', 'question', 'questionner', 'quete', 'queter', 'queue',
    'qui', 'quiconque', 'quiet', 'quille', 'quincaillerie', 'quinine', 'quinquennal', 'quintal',
    'quinte', 'quintuple', 'quinze', 'quinzaine', 'quittance', 'quitte', 'quitter', 'quoi',
    'race', 'rachat', 'racheter', 'racine', 'racisme', 'racler', 'raconter', 'radar',
    'rade', 'radeau', 'radiateur', 'radiation', 'radical', 'radier', 'radieux', 'radin',
    'radio', 'radiographie', 'radis', 'radoter', 'radoucir', 'rafale', 'raffiner', 'raffoler',
    'rafistoler', 'rafle', 'rafler', 'rafraichir', 'rage', 'rager', 'ragout', 'raide',
    // S
    'sable', 'sabler', 'sableux', 'sablier', 'sablon', 'sablonner', 'saborder', 'sabot',
    'sabre', 'sabrer', 'sacrer', 'sacrifice', 'sacrifier', 'sacrilege', 'sacristie', 'sadique',
    'safari', 'safran', 'saga', 'sagace', 'sage', 'sagesse', 'sagittaire', 'saigner',
    'saillant', 'saillie', 'saillir', 'sain', 'saindoux', 'saint', 'saisie', 'saisir',
    'saison', 'salade', 'salaire', 'salarie', 'sale', 'saler', 'salir', 'salive',
    'salle', 'salon', 'salope', 'salopette', 'saltimbanque', 'salubre', 'saluer', 'salut',
    'salutaire', 'salutation', 'salvateur', 'salve', 'samedi', 'sanatorium', 'sanctifier', 'sanction',
    'sanctuaire', 'sandale', 'sandwich', 'sang', 'sanglant', 'sangle', 'sanglier', 'sanglot',
    'sangloter', 'sangsue', 'sanguin', 'sanitaire', 'sans', 'sante', 'saper', 'sapeur',
    'sapin', 'sarbacane', 'sarcasme', 'sarcler', 'sarde', 'sardine', 'satan', 'satellite',
    // T
    'tabac', 'tabatiere', 'tabernacle', 'table', 'tableau', 'tablette', 'tablier', 'tabou',
    'tabouret', 'tache', 'tacher', 'tachete', 'tacite', 'taciturne', 'tacot', 'tact',
    'tactile', 'tactique', 'taffetas', 'taie', 'taille', 'tailler', 'tailleur', 'taillis',
    'tain', 'taire', 'talc', 'talent', 'talentueux', 'talisman', 'talocher', 'talon',
    'talonner', 'talus', 'tamarin', 'tamaris', 'tambour', 'tambourin', 'tamis', 'tamisé',
    'tamiser', 'tampon', 'tamponner', 'tandem', 'tandis', 'tangage', 'tangent', 'tangible',
    'tango', 'tanguer', 'taniere', 'tank', 'tanner', 'tannerie', 'tanneur', 'tant',
    'tante', 'tantinet', 'tantot', 'taon', 'tapage', 'tapageur', 'tape', 'taper',
    'tapette', 'tapin', 'tapinois', 'tapioca', 'tapir', 'tapis', 'tapisser', 'tapisserie',
    'tapoter', 'taquin', 'taquiner', 'tarabuster', 'tard', 'tarder', 'tardif', 'tare',
    // U-V
    'unanime', 'uni', 'unifier', 'uniforme', 'union', 'unique', 'unir', 'unisson',
    'unite', 'univers', 'universel', 'universite', 'uranium', 'urbain', 'urbanisme', 'urgence',
    'urgent', 'urine', 'uriner', 'urinoir', 'urne', 'us', 'usage', 'use',
    'usé', 'user', 'usinage', 'usine', 'usité', 'ustensile', 'usuel', 'usufruit',
    'usure', 'usurier', 'usurper', 'utile', 'utiliser', 'utilite', 'utopie', 'uvée',
    'vacance', 'vacant', 'vacarme', 'vaccin', 'vacciner', 'vache', 'vacherie', 'vaciller',
    'vagabond', 'vagabonder', 'vagin', 'vague', 'vaguement', 'vaillant', 'vain', 'vaincre',
    'vaincu', 'vainement', 'vainqueur', 'vaisseau', 'vaisselle', 'valable', 'valet', 'valeur',
    'valeureux', 'valide', 'valider', 'validite', 'valise', 'vallee', 'vallon', 'valoir',
    'valoriser', 'valse', 'valser', 'valve', 'vampire', 'vandale', 'vanille', 'vanite',
    // W-X-Y-Z
    'wagon', 'wagonnet', 'wallon', 'watt', 'western', 'whisky', 'wifi',
    'xénophobe', 'xylophone',
    'yacht', 'yaourt', 'yard', 'yen', 'yeux', 'yoga', 'yogi', 'youpi',
    'yoyo',
    'zapper', 'zebre', 'zebrure', 'zelateur', 'zele', 'zénith', 'zero', 'zeste',
    'zester', 'zibeline', 'zigzag', 'zigzaguer', 'zinc', 'zinzin', 'zipper', 'zizanie',
    'zodiaque', 'zombie', 'zone', 'zoner', 'zoo', 'zoologie', 'zoom', 'zozoter'
];

const wordListsEN = [
    // A
    'abandon', 'ability', 'able', 'about', 'above', 'absent', 'absorb', 'abstract',
    'absurd', 'abuse', 'access', 'accident', 'account', 'accuse', 'achieve', 'acid',
    'acoustic', 'acquire', 'across', 'action', 'actor', 'actress', 'actual', 'adapt',
    'address', 'adjust', 'admit', 'adult', 'advance', 'advice', 'aerobic', 'affair',
    'afford', 'afraid', 'after', 'again', 'against', 'agency', 'agent', 'agree',
    'ahead', 'aircraft', 'airport', 'aisle', 'alarm', 'album', 'alcohol', 'alert',
    'alien', 'alley', 'allow', 'almost', 'alone', 'alpha', 'already', 'also',
    'alter', 'always', 'amateur', 'amazing', 'among', 'amount', 'amused', 'analyst',
    'anchor', 'ancient', 'anger', 'angle', 'angry', 'animal', 'ankle', 'announce',
    'annual', 'another', 'answer', 'antenna', 'antique', 'anxiety', 'apart', 'apology',
    'appear', 'apple', 'approve', 'april', 'aquarium', 'arbiter', 'arcade', 'arctic',
    // B
    'baby', 'bachelor', 'bacon', 'badge', 'balance', 'balcony', 'ball', 'bamboo',
    'banana', 'banner', 'bargain', 'barrel', 'basic', 'basket', 'battle', 'beach',
    'beauty', 'because', 'become', 'before', 'begin', 'behave', 'behind', 'believe',
    'below', 'bench', 'benefit', 'better', 'between', 'beyond', 'bicycle', 'biology',
    'bitter', 'black', 'blade', 'blame', 'blanket', 'blast', 'bleak', 'bless',
    'blind', 'blood', 'blossom', 'blouse', 'board', 'border', 'boring', 'borrow',
    'bottle', 'bottom', 'bounce', 'bracket', 'brain', 'brand', 'brave', 'bread',
    'breeze', 'brick', 'bridge', 'brief', 'bright', 'bring', 'brisk', 'broccoli',
    'broken', 'bronze', 'broom', 'brother', 'brown', 'brush', 'bubble', 'buddy',
    'budget', 'buffalo', 'build', 'bundle', 'bunker', 'burden', 'burger', 'burst',
    'business', 'busy', 'butter', 'buyer', 'buzz',
    // C
    'cabbage', 'cabin', 'cable', 'cactus', 'cage', 'calendar', 'camera', 'camp',
    'canal', 'cancel', 'candle', 'candy', 'cannon', 'canoe', 'canvas', 'canyon',
    'capable', 'capital', 'captain', 'carbon', 'career', 'careful', 'cargo', 'carpet',
    'carry', 'cartoon', 'cascade', 'casino', 'castle', 'casual', 'catalog', 'catch',
    'category', 'cattle', 'caught', 'cause', 'caution', 'ceiling', 'celery', 'cement',
    'census', 'century', 'cereal', 'certain', 'chair', 'chalk', 'champion', 'change',
    'chaos', 'chapter', 'charge', 'chase', 'cheap', 'check', 'cheese', 'cherry',
    'chest', 'chicken', 'chief', 'child', 'chimney', 'choice', 'choose', 'chronic',
    'chuckle', 'chunk', 'churn', 'cigar', 'cinnamon', 'circle', 'citizen', 'civil',
    'claim', 'clarify', 'clerk', 'clever', 'click', 'client', 'climb', 'clinic',
    'clock', 'close', 'cloth', 'cloud', 'clown', 'clutch', 'coach', 'coast',
    // D
    'damage', 'dance', 'danger', 'daring', 'darwin', 'daughter', 'decade', 'december',
    'decide', 'decline', 'decorate', 'decrease', 'defeat', 'defend', 'define', 'defy',
    'degree', 'delay', 'deliver', 'demand', 'demise', 'denial', 'dentist', 'depart',
    'depend', 'deposit', 'depth', 'deputy', 'derive', 'describe', 'desert', 'design',
    'despair', 'destroy', 'detail', 'detect', 'develop', 'device', 'devote', 'diagram',
    'diamond', 'diary', 'dice', 'diesel', 'differ', 'digital', 'dignity', 'dilemma',
    'dinner', 'dinosaur', 'direct', 'dirt', 'disagree', 'discover', 'disease', 'dish',
    'dismiss', 'disorder', 'display', 'distance', 'divert', 'divide', 'divorce', 'dizzy',
    'doctor', 'document', 'dolphin', 'domain', 'donate', 'donkey', 'donor', 'double',
    'dove', 'draft', 'dragon', 'drama', 'drastic', 'draw', 'dream', 'dress',
    'drift', 'drill', 'drink', 'drip', 'drive', 'drop', 'drum', 'drunk',
    // E
    'eager', 'eagle', 'early', 'earth', 'easily', 'eastern', 'ecology', 'economy',
    'educate', 'effort', 'eight', 'either', 'elbow', 'elder', 'electric', 'elegant',
    'element', 'elephant', 'elevator', 'elite', 'embark', 'embody', 'embrace', 'emerge',
    'emotion', 'employ', 'empower', 'empty', 'enable', 'enact', 'encounter', 'encourage',
    'endless', 'endorse', 'enemy', 'energy', 'enforce', 'engage', 'engine', 'enhance',
    'enjoy', 'enlist', 'enough', 'enrich', 'enroll', 'ensure', 'enter', 'entire',
    'entry', 'envelope', 'episode', 'equal', 'equip', 'erode', 'erosion', 'error',
    'erupt', 'escape', 'essay', 'essence', 'estate', 'eternal', 'ethics', 'evidence',
    'evil', 'evoke', 'evolve', 'exact', 'example', 'exceed', 'excel', 'except',
    'excess', 'exchange', 'excite', 'exclude', 'excuse', 'execute', 'exercise', 'exhaust',
    'exhibit', 'exile', 'exist', 'expand', 'expect', 'expire', 'explain', 'expose',
    // F
    'fabric', 'fabulous', 'facility', 'factor', 'faculty', 'failure', 'falcon', 'false',
    'family', 'famous', 'fantasy', 'farmer', 'fashion', 'father', 'fatigue', 'fault',
    'favorite', 'feature', 'february', 'federal', 'feedback', 'feeling', 'female', 'fence',
    'festival', 'fiction', 'field', 'figure', 'filter', 'final', 'finance', 'finger',
    'finish', 'fiscal', 'fitness', 'flame', 'flash', 'flavor', 'flight', 'float',
    'flower', 'fluid', 'flush', 'focus', 'follow', 'forest', 'forget', 'fortune',
    'forward', 'fossil', 'foster', 'fragile', 'frame', 'frequent', 'fresh', 'friend',
    'fringe', 'frown', 'frozen', 'fruit', 'furnace', 'future',
    // G
    'gadget', 'galaxy', 'gallery', 'garden', 'garlic', 'gather', 'gauge', 'general',
    'genius', 'gentle', 'genuine', 'gesture', 'ghost', 'giant', 'gift', 'giggle',
    'ginger', 'giraffe', 'give', 'glad', 'glance', 'glare', 'glass', 'glide',
    'glimpse', 'globe', 'gloom', 'glory', 'glove', 'glucose', 'glue', 'goal',
    'goddess', 'golden', 'govern', 'grace', 'grain', 'grand', 'grant', 'grape',
    'grass', 'grateful', 'gravity', 'great', 'green', 'grid', 'grief', 'grocery',
    'group', 'growth', 'guard', 'guess', 'guide', 'guilty', 'guitar', 'govern',
    // H
    'habitat', 'hammer', 'hamster', 'happy', 'harbor', 'hardly', 'harvest', 'hazard',
    'health', 'heavy', 'hedgehog', 'height', 'hello', 'helmet', 'hidden', 'highlight',
    'history', 'hobby', 'hockey', 'holiday', 'hollow', 'honey', 'honor', 'horizon',
    'horror', 'horse', 'hospital', 'hotel', 'hover', 'human', 'humble', 'humor',
    'hundred', 'hungry', 'hunter', 'hurdle', 'hurry', 'husband', 'hybrid', 'hydrogen',
    // I-J
    'ideal', 'identify', 'ignore', 'illegal', 'illness', 'image', 'imitate', 'immense',
    'immune', 'impact', 'impose', 'improve', 'impulse', 'inch', 'include', 'income',
    'increase', 'index', 'indicate', 'indoor', 'industry', 'infant', 'inflict', 'inform',
    'inherit', 'initial', 'inject', 'injury', 'innocent', 'input', 'inquiry', 'insane',
    'insect', 'inside', 'inspire', 'install', 'intact', 'interest', 'into', 'invest',
    'invite', 'involve', 'island', 'isolate', 'issue', 'jacket', 'jaguar', 'january',
    'jealous', 'jelly', 'jewel', 'journey', 'judge', 'juice', 'july', 'jungle',
    'junior', 'just', 'justice', 'kangaroo', 'keen', 'kidney', 'kitchen', 'kiwi',
    // K-L-M
    'kitten', 'knee', 'knife', 'knock', 'know', 'label', 'labor', 'ladder',
    'lady', 'lagoon', 'language', 'laptop', 'large', 'later', 'latin', 'laugh',
    'laundry', 'lava', 'lawsuit', 'layer', 'lazy', 'leader', 'league', 'learn',
    'leather', 'lecture', 'legal', 'legend', 'leisure', 'lemon', 'length', 'leopard',
    'lesson', 'letter', 'level', 'liberty', 'library', 'license', 'lifestyle', 'light',
    'limit', 'linger', 'lion', 'liquid', 'listen', 'little', 'living', 'lizard',
    'local', 'logic', 'lonely', 'loyal', 'lucky', 'luggage', 'lumber', 'lunar',
    'luxury', 'machine', 'magic', 'magnet', 'major', 'make', 'mammal', 'manage',
    'mandate', 'mango', 'mansion', 'manual', 'maple', 'marble', 'march', 'margin',
    'marine', 'market', 'marriage', 'master', 'match', 'material', 'matrix', 'matter',
    'maximum', 'maze', 'meadow', 'measure', 'mechanic', 'medal', 'media', 'melody',
    'member', 'memory', 'mention', 'menu', 'merchant', 'mercy', 'merge', 'merit',
    // N-O
    'merry', 'method', 'middle', 'midnight', 'military', 'million', 'mimic', 'mineral',
    'minimum', 'minor', 'minute', 'miracle', 'mirror', 'misery', 'mistake', 'mixture',
    'mobile', 'model', 'modify', 'moment', 'monitor', 'monster', 'month', 'moral',
    'morning', 'mosquito', 'mother', 'motion', 'motor', 'mountain', 'mouse', 'movie',
    'music', 'mystery', 'naked', 'name', 'narrow', 'nation', 'nature', 'navy',
    'near', 'neck', 'negative', 'neighbor', 'nephew', 'nerve', 'nest', 'network',
    'neutral', 'never', 'news', 'next', 'nice', 'night', 'noble', 'noise',
    'nominee', 'normal', 'north', 'notice', 'novel', 'november', 'number', 'nurse',
    'object', 'oblige', 'obscure', 'observe', 'obtain', 'obvious', 'occur', 'ocean',
    'october', 'odor', 'offense', 'offer', 'office', 'often', 'olympic', 'omit',
    'online', 'open', 'opera', 'opinion', 'oppose', 'option', 'orange', 'orbit',
    'order', 'ordinary', 'organ', 'orient', 'origin', 'orphan', 'ostrich', 'other',
    // P-Q-R
    'outdoor', 'outer', 'output', 'outside', 'oval', 'oven', 'owner', 'oxygen',
    'oyster', 'package', 'paddle', 'panda', 'panel', 'panic', 'paper', 'parade',
    'parent', 'parking', 'parrot', 'party', 'passage', 'passion', 'patch', 'patient',
    'pattern', 'pause', 'payment', 'peace', 'peanut', 'peasant', 'pelican', 'penalty',
    'pencil', 'people', 'pepper', 'perfect', 'permit', 'person', 'physics', 'piano',
    'picture', 'piece', 'pilot', 'pioneer', 'planet', 'plastic', 'plate', 'plateau',
    'plunge', 'poem', 'point', 'polar', 'police', 'pond', 'pony', 'popular',
    'portion', 'position', 'possible', 'potato', 'pottery', 'poverty', 'powder', 'power',
    'practice', 'praise', 'predict', 'prefer', 'prepare', 'present', 'pretty', 'prevent',
    'price', 'pride', 'primary', 'print', 'prison', 'private', 'prize', 'problem',
    'process', 'produce', 'profit', 'program', 'project', 'promote', 'proof', 'property',
    'prosper', 'protect', 'proud', 'provide', 'public', 'pudding', 'pulse', 'pump',
    'punch', 'pupil', 'puppy', 'purchase', 'purple', 'purpose', 'purse', 'push',
    'puzzle', 'pyramid', 'quality', 'quantum', 'quarter', 'question', 'quick', 'quiet',
    'quit', 'quiz', 'quote', 'rabbit', 'raccoon', 'radar', 'radio', 'railway',
    'rainbow', 'raise', 'rally', 'ramp', 'ranch', 'random', 'range', 'rapid',
    'rare', 'rate', 'rather', 'raven', 'razor', 'ready', 'real', 'reason',
    'rebel', 'rebuild', 'recall', 'receive', 'recipe', 'record', 'recycle', 'reduce',
    // S
    'reflect', 'reform', 'refuse', 'region', 'regret', 'regular', 'reject', 'relax',
    'release', 'relief', 'rely', 'remain', 'remember', 'remind', 'remove', 'render',
    'renew', 'rental', 'repair', 'repeat', 'replace', 'report', 'require', 'rescue',
    'resemble', 'resist', 'resource', 'response', 'result', 'retire', 'retreat', 'return',
    'reunion', 'reveal', 'review', 'reward', 'rhythm', 'ribbon', 'rifle', 'right',
    'rigid', 'river', 'road', 'robot', 'robust', 'rocket', 'romance', 'rookie',
    'rough', 'round', 'route', 'royal', 'rubber', 'rude', 'rumor', 'rural',
    'saddle', 'sadness', 'safari', 'safety', 'salad', 'salmon', 'salon', 'salt',
    'salute', 'sample', 'sand', 'satisfy', 'satoshi', 'sauce', 'sausage', 'savage',
    'scale', 'scandal', 'scene', 'scheme', 'school', 'science', 'scissors', 'scorpion',
    'scout', 'scrap', 'screen', 'script', 'scrub', 'search', 'season', 'second',
    'secret', 'section', 'security', 'segment', 'select', 'senior', 'sentence', 'series',
    'service', 'session', 'settle', 'setup', 'seven', 'shadow', 'shaft', 'shallow',
    // T
    'share', 'shed', 'shell', 'sheriff', 'shield', 'shift', 'shine', 'ship',
    'shiver', 'shock', 'short', 'shoulder', 'shove', 'shrimp', 'shrug', 'shuffle',
    'sibling', 'side', 'siege', 'sight', 'sign', 'silent', 'silk', 'silly',
    'silver', 'similar', 'simple', 'since', 'sing', 'sister', 'situate', 'sketch',
    'skill', 'skin', 'skirt', 'skull', 'slab', 'slam', 'sleep', 'slender',
    'slice', 'slide', 'slight', 'slim', 'slogan', 'slot', 'slow', 'slush',
    'small', 'smart', 'smile', 'smoke', 'smooth', 'snack', 'snake', 'snap',
    'sniff', 'snow', 'soap', 'soccer', 'social', 'sock', 'soda', 'soft',
    'solar', 'soldier', 'solid', 'solution', 'solve', 'someone', 'song', 'soon',
    'sorry', 'sort', 'soul', 'sound', 'source', 'south', 'space', 'spare',
    'spatial', 'spawn', 'speak', 'special', 'speed', 'spell', 'spend', 'sphere',
    'spider', 'spike', 'spin', 'spirit', 'split', 'sponsor', 'spoon', 'sport',
    'spray', 'spread', 'spring', 'spy', 'square', 'squeeze', 'squirrel', 'stable',
    'stadium', 'staff', 'stage', 'stairs', 'stamp', 'stand', 'start', 'state',
    'stay', 'steak', 'steel', 'stem', 'step', 'stereo', 'stick', 'still',
    'stock', 'stomach', 'stone', 'stool', 'story', 'stove', 'strategy', 'street',
    'strike', 'strong', 'struggle', 'student', 'stuff', 'stumble', 'style', 'subject',
    'submit', 'subway', 'success', 'such', 'sudden', 'suffer', 'sugar', 'suggest',
    'suit', 'summer', 'sunny', 'sunset', 'super', 'supply', 'supreme', 'surface',
    'surge', 'surprise', 'surround', 'survey', 'suspect', 'sustain', 'swallow', 'swamp',
    'swap', 'swarm', 'symbol', 'symptom', 'syrup', 'system', 'table', 'tackle',
    'talent', 'tank', 'tape', 'target', 'task', 'taste', 'tattoo', 'taxi',
    'teach', 'team', 'tell', 'temple', 'tenant', 'tennis', 'tent', 'term',
    'test', 'text', 'thank', 'theater', 'theme', 'theory', 'there', 'they',
    'thing', 'think', 'third', 'thought', 'three', 'thrive', 'throw', 'thumb',
    'thunder', 'ticket', 'tiger', 'timber', 'title', 'toast', 'tobacco', 'today',
    'together', 'toilet', 'token', 'tomato', 'tomorrow', 'tonight', 'total', 'touch',
    'tough', 'tourist', 'toward', 'tower', 'town', 'track', 'trade', 'traffic',
    'tragic', 'train', 'transfer', 'trap', 'trash', 'travel', 'tray', 'treat',
    'tree', 'trend', 'trial', 'tribe', 'trick', 'trigger', 'trim', 'trip',
    'trophy', 'trouble', 'truck', 'true', 'truly', 'trumpet', 'trust', 'truth',
    'tube', 'tuition', 'tumble', 'tuna', 'tunnel', 'turkey', 'turn', 'turtle',
    'twelve', 'twenty', 'twice', 'twin', 'twist', 'typical', 'ugly', 'umbrella',
    // U-V-W-X-Y-Z
    'unable', 'unaware', 'uncle', 'uncover', 'under', 'undo', 'unfair', 'unfold',
    'unhappy', 'uniform', 'unique', 'unit', 'universe', 'unknown', 'unlock', 'until',
    'unusual', 'unveil', 'unwrap', 'update', 'upgrade', 'uphold', 'upon', 'upper',
    'upset', 'urban', 'urge', 'usage', 'useful', 'useless', 'usual', 'utility',
    'vacant', 'vacuum', 'vague', 'valid', 'valley', 'valve', 'vampire', 'vanish',
    'vapor', 'various', 'vast', 'vault', 'vector', 'vehicle', 'velvet', 'vendor',
    'venture', 'venue', 'verb', 'verify', 'version', 'very', 'vessel', 'veteran',
    'viable', 'vibrant', 'vicious', 'victory', 'video', 'view', 'village', 'vintage',
    'violin', 'virtual', 'virus', 'visa', 'visit', 'visual', 'vital', 'vivid',
    'vocal', 'voice', 'void', 'volcano', 'volume', 'vote', 'voyage', 'wage',
    'wagon', 'waist', 'wait', 'walk', 'wall', 'walnut', 'want', 'warfare',
    'warm', 'warrior', 'wash', 'wasp', 'waste', 'watch', 'water', 'wave',
    'wealth', 'weapon', 'weather', 'wedding', 'weekend', 'weight', 'welcome', 'welfare',
    'west', 'whale', 'wheat', 'wheel', 'when', 'where', 'while', 'whisper',
    'wide', 'width', 'wife', 'wild', 'window', 'wine', 'wing', 'winter',
    'wisdom', 'wise', 'wish', 'witness', 'wolf', 'woman', 'wonder', 'wood',
    'word', 'work', 'world', 'worry', 'worth', 'wrap', 'wreck', 'wrestle',
    'wrist', 'write', 'wrong', 'yacht', 'yard', 'year', 'yellow', 'young',
    'youth', 'zebra', 'zero', 'zone', 'zoo'
];

// Exporter les listes de mots selon la langue
function getWordList(language = 'fr') {
    // Supporter 'fr' et 'en' comme codes de langue
    return language === 'en' ? wordListsEN : wordListsFR;
}

